# Site settings
title: Scott Bobbitt | Rails Developer
email: scottebobbitt@gmail.com
description: Ruby on Rails Developer
baseurl: ""
url: "http://scottebobbitt.me"
permalink: /blog/:title/
# url: http://localhost:4000
# permalink: /:title/
twitter_username: scottebobbitt
github_username:  sco-bo
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
kramdown: 
  input: GFM
  syntax_highlighter: rouge
