# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Bobbitt | Developer
email: scottebobbitt@gmail.com
description: Ruby on Rails Developer
baseurl: ""
url: "http://scottebobbitt.me"
twitter_username: scottebobbitt
github_username:  sco-bo

# Build settings
markdown: kramdown
