# Site settings
title: Scott Bobbitt | Developer
email: scottebobbitt@gmail.com
description: Ruby on Rails Developer
baseurl: ""
url: "http://scottebobbitt.me"
twitter_username: scottebobbitt
github_username:  sco-bo
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown


